version: '3.8'

services:

  db:
    image: postgres:14.1
    volumes:
      - ./init-pg:/docker-entrypoint-initdb.d:cached
      - ./volumes/postgresql/14/data:/var/lib/postgresql/data:delegated
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

  studytube:
    build:
      context: ${PWD}
      dockerfile: Dockerfile.dev
    image: studytube_test:dev
    command: bundle exec rails s -p 3000 -b 0.0.0.0
    env_file:
      - .env
    volumes:
      - ${PWD}:/var/www/app:cached
    ports:
      - 3000:3000
    depends_on:
      - db
    tty: true
    stdin_open: true
